#install.packages(c("tidyverse", "lme4", "lmerTest", "data.table"))
library(tidyverse)
library(lme4)
library(lmerTest)    
library(data.table)  

print("1. Loading RT Data...")
rt_data <- fread("/Users/chenyanze/NS-analysis/naturalstories/naturalstories_RTS/processed_RTs.tsv")


print("2. Loading Freq data and performing Logarithmic calculation")
freq1_data <- fread("/Users/chenyanze/NS-analysis/naturalstories/freqs/freqs-1.tsv", header = FALSE, 
                    col.names = c("token_code", "n_order", "word", "freq_n", "freq_n_minus_1")) %>%
  filter(grepl("\\.word$", token_code)) %>%    # Only keep the tokens with .word suffix to prevent double counting
  separate(token_code, into = c("item", "zone", "type"), sep = "\\.") %>%
  mutate(
    item = as.numeric(item),
      zone = as.numeric(zone),
    log_freq = log(freq_n)                     
  ) %>%
  select(item, zone, word, log_freq)

print("3. Aligning and merging the data")
final_model_data <- rt_data %>%
  inner_join(freq1_data, by = c("item", "zone", "word")) %>% # merge the rt data with frequency data
  filter(is.finite(log_freq))                  # prevent some misspelling word with 0 frequency since ln(0) is negative infinity


print("4. Fitting a mixed-effects regression model...")

model <- lmer(RT ~ log_freq + (1 | WorkerId) + (1 | item), # Use Linear Mixed-Effects Regression to consider random effect such as different readers and stories
              data = final_model_data)

summary(model)


# > summary(model)
# Linear mixed model fit by REML. t-tests use Satterthwaite's method [
# lmerModLmerTest]
# Formula: RT ~ log_freq + (1 | WorkerId) + (1 | item)
#    Data: final_model_data
# 
# REML criterion at convergence: 9362237
# 
# Scaled residuals: 
#     Min      1Q  Median      3Q     Max 
# -3.3648 -0.4506 -0.1780  0.1656 19.4106 
# 
# Random effects:
#  Groups   Name        Variance Std.Dev.
#  WorkerId (Intercept)  6648.0   81.54  
#  item     (Intercept)   121.1   11.01  
#  Residual             20307.6  142.50  
# Number of obs: 733810, groups:  WorkerId, 180; item, 10
# 
# Fixed effects:
#               Estimate Std. Error         df t value Pr(>|t|)    
# (Intercept)  3.664e+02  7.093e+00  1.049e+02   51.65   <2e-16 ***
# log_freq    -1.864e+00  5.562e-02  7.336e+05  -33.51   <2e-16 ***
# ---
# Signif. codes:  0 ‘***’ 0.001 ‘**’ 0.01 ‘*’ 0.05 ‘.’ 0.1 ‘ ’ 1
# 
# Correlation of Fixed Effects:
#          (Intr)
# log_freq -0.146”